name: CI/CD Docker Push - Service Discovery

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get version from number of merged PRs
        id: version
        run: |
          PR_COUNT=$(gh pr list --state merged --base main --json number --jq 'length')
          VERSION="0.1.$PR_COUNT"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version set to $VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push Docker image for multiple architectures
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.DOCKER_USERNAME }}/service-discovery:${{ env.VERSION }}
            ${{ env.DOCKER_USERNAME }}/service-discovery:latest
